In [1]:
import numpy as np
import cv2 as cv
import matplotlib.pylab as plt
from camcar_new import *
import time


car = CamCar()

In [ ]:


img = car.get_prep_image()
plt.imshow(img)



In [ ]:

line_segments = car.calc_line_segments(img)
print(line_segments)

In [ ]:
lane_lines = car.average_slope_intercept(img, line_segments)
print('average_slope_intercept:')
print(lane_lines)

In [ ]:
print(img.shape)

In [ ]:

fahrlinie = car.calc_fahrlinie(img, lane_lines)
#print((fahrlinie[0], fahrlinie[1]), (fahrlinie[2], fahrlinie[3]))

In [ ]:
imageresult = car.draw_line_segments(lane_lines, fahrlinie, img)
plt.imshow(imageresult)

In [ ]:
lenkwinkel = car.compute_steering_angle(img, lane_lines)


In [2]:
# Video-Schleife
while True:
    img = car.get_prep_image()
    line_segments = car.calc_line_segments(img)
    print(line_segments)
    
    if line_segments is not None:
        lane_lines = car.average_slope_intercept(img, line_segments)
        print('average_slope_intercept:')
        print(lane_lines)
        fahrlinie = car.calc_fahrlinie(img, lane_lines)
        imageresult = car.draw_line_segments(lane_lines, fahrlinie, img)
        lenkwinkel = car.compute_steering_angle(img, lane_lines)
        cv.imshow("Display window (press q to quit)", imageresult)
        # Ende bei Drücken der Taste q
        if cv.waitKey(1) == ord('q'):
            break
        time.sleep(0.3)
        
    else:
        print('Stop - Keine Linien mehr erkannt.')
        break
   
car.close()
cv.destroyAllWindows()

[[[ 82  95  91  81]]

 [[467  10 506  59]]

 [[ 55 139  71 109]]

 [[550 125 583 187]]

 [[450  11 519 113]]

 [[115  23 125  11]]

 [[ 51  66  55  55]]

 [[ 24 198  39 169]]

 [[119  41 151   4]]

 [[ 31 183  65 119]]

 [[542 155 563 199]]

 [[ 27 138  59  90]]

 [[581  55 595  70]]

 [[446   7 460  27]]

 [[ 75  65  91  48]]

 [[ 87  85 116  46]]

 [[  1 187   9 171]]

 [[538   1 545  10]]

 [[507  60 543 113]]

 [[539  10 550  21]]

 [[522 119 536 145]]

 [[550   3 556  15]]

 [[ 79  63  91  49]]

 [[ 91  47 111  27]]

 [[551  22 566  39]]

 [[107  29 121  15]]

 [[578  40 595  57]]

 [[ 68 116  76 102]]

 [[591  70 598  79]]

 [[534 139 541 154]]

 [[ 14 151  18 143]]

 [[570 159 575 170]]

 [[462  27 491  70]]

 [[503  88 509  99]]

 [[589  36 594  47]]

 [[ 54  69  56  77]]

 [[106  60 113  51]]

 [[546 119 556 137]]

 [[555 183 561 195]]

 [[587  62 593  71]]

 [[ 25 143  31 134]]

 [[119  19 133   3]]

 [[578  41 594  57]]

 [[ 43 158  51 143]]

 [[515 110 523 122]]

 [[561 146