In [1]:
import numpy as np
import cv2 as cv
import matplotlib.pylab as plt
from camcar_new import *
import time


car = CamCar()

car.drive(30, 1)
car.steering_angle = 90

# Video-Schleife
while True:
    img = car.get_prep_image()
    line_segments = car.calc_line_segments(img)
    print(line_segments)
    
    if line_segments is not None:
        lane_lines = car.average_slope_intercept(img, line_segments)
        print('average_slope_intercept:')
        print(lane_lines)
        fahrlinie = car.calc_fahrlinie(img, lane_lines)
        imageresult = car.draw_line_segments(lane_lines, fahrlinie, img)
        lenkwinkel = car.compute_steering_angle(img, lane_lines)
        car.steering_angle = lenkwinkel
        cv.imshow("Display window (press q to quit)", imageresult)
        # Ende bei Drücken der Taste q
        if cv.waitKey(1) == ord('q'):
            break
        time.sleep(0.3)
    
    else:
        car.stop()
        car.close()
        print('Stop - Keine Linien mehr erkannt.')
        break

car.stop()
car.close()
cv.destroyAllWindows()

[[[514 111 532 143]]

 [[543 111 591 198]]

 [[ 31 170  51 137]]

 [[479  60 511 106]]

 [[106  47 119  24]]

 [[559  28 598  69]]

 [[ 19 198  23 190]]

 [[543 113 560 143]]

 [[479  29 487  37]]

 [[544   1 561  18]]

 [[515  69 527  81]]

 [[466  15 473  23]]

 [[ 55   0  67  34]]

 [[  7 166  19 143]]

 [[ 87  75  91  65]]

 [[ 81  47  95  33]]

 [[ 94  63  99  55]]

 [[ 75 102  79  94]]

 [[515  70 526  82]]

 [[527  86 535  93]]

 [[423   0 435   8]]

 [[565  16 571  24]]

 [[487  40 503  55]]

 [[102  18 105   9]]

 [[  2   9   3  19]]

 [[562  19 570  27]]

 [[504  55 523  72]]

 [[529 135 543 159]]

 [[ 86  76  93  63]]

 [[549  11 558  19]]

 [[453  26 463  38]]

 [[ 95  63 107  43]]

 [[575  44 583  52]]

 [[531 139 563 197]]

 [[458   9 472  23]]

 [[579  34 589  47]]

 [[458  31 479  58]]

 [[ 15 134  18 144]]

 [[539 101 543 109]]

 [[  3 118  15 130]]

 [[467  16 487  36]]

 [[ 72  47  83  47]]

 [[ 98  27 101  19]]

 [[567  38 579  50]]

 [[119  22 123  14]]

 [[ 63  24

/home/pi/.local/lib/python3.7/site-packages/numpy/lib/function_base.py:380: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/home/pi/.local/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


IndexError: list index out of range